### ISSUE TITLE
US3 Add UI (button + view of endorsed text) for endorsing posts

### ISSUE THREAD

**Issue by lukenalewajk** [CMU-313/nodebb-f24-team-software-stars#10] opened 2024-09-13 02:12 UTC
Effort: low
Acceptance Criteria: An admin can see and click on a button that will mark the topic/main post as endorsed. A non-admin will not see this button. An endorsed post will have a label/UI stating that it is endorsed.

**Comment by ldlin1** [comment] 2024-09-18 00:26
This is a duplicate of #11

**Comment by veronicabenedict** [comment] 2024-09-25 00:16
This feature (US3) will be implemented if we hit a roadblock for implementing US1. Else, this issue will be closed as not planned before the end of sprint 2.

**Closed as completed** 2024-10-11 00:59 UTC
Labels: enhancement
