### ISSUE TITLE
US2 Add UI change for answered/unanswered questions by a professor

### ISSUE THREAD

**Issue by veronicabenedict** [CMU-313/nodebb-f24-team-software-stars#7] opened 2024-09-13 02:10 UTC
Effort: low to medium
Acceptance Criteria: a post being shown as unanswered when no professor has added a post to it, and then a professor adding a post and the topic now being shown as answered

**Comment by veronicabenedict** [comment] 2024-09-13 02:11
Effort: Low
Acceptance Criteria: be able to see which replies have been unanswered and answered

**Comment by etong11** [comment] 2024-09-18 00:22
Duplicate of #8 - Combining UI change issue with the back-end feature so that back-end code can be developed and tested through front-end UI

**Comment by veronicabenedict** [comment] 2024-09-18 00:25
this issue is closed. the UI change will be worked on through the issue #8 (comment has been added there)

**Closed as completed** 2024-10-11 02:36 UTC
Labels: enhancement
