### ISSUE TITLE
US3 Add logic for post endorsements (only done by teaching staff, hooking button to code)

### ISSUE THREAD

**Issue by lukenalewajk** [CMU-313/nodebb-f24-team-software-stars#11] opened 2024-09-13 02:13 UTC
Effort: low
Acceptance Criteria: A professor (user with admin permissions) is able to mark a post/reply within a topic as endorsed by a professor.

**Comment by veronicabenedict** [comment] 2024-09-25 00:16
This feature (US3) will be implemented if we hit a roadblock for implementing US1. Else, this issue will be closed as not planned before the end of sprint 2.

**Comment by etong11** [comment] 2024-10-02 00:38
Broke feature into smaller features:
Duplicate of #36 and Duplicate of #37

**Closed as not planned by etong11** 2024-10-02 00:38 UTC
Labels: enhancement
